export default function () {
  return {
    list: [
      { id: 1, photo: "", name: "Любимова Анна Владиславовна", manager: 1 },
      { id: 2, photo: "", name: "Зубкова София Дмитриевна", manager: 2 },
      { id: 3, photo: "", name: "Кузьмина Мия Владимировна", manager: 1 },
      { id: 4, photo: "", name: "Соколов Александр Фёдорович", manager: 4 },
      { id: 5, photo: "", name: "Соколова Полина Тимофеевна", manager: 1 },
      { id: 6, photo: "", name: "Панков Артём Максимович", manager: 2 },
      { id: 7, photo: "", name: "Петухова София Ярославовна", manager: 3 },
      { id: 8, photo: "", name: "Николаев Марк Константинович", manager: 4 },
      { id: 9, photo: "", name: "Кузнецова Юлия Павловна", manager: 2 },
      { id: 10, photo: "", name: "Блинов Александр Александрович", manager: 2 },
      { id: 11, photo: "", name: "Макаров Михаил Глебович", manager: 1 },
      { id: 12, photo: "", name: "Павлова Василиса Вячеславовна", manager: 1 },
      { id: 13, photo: "", name: "Горбунов Фёдор Даниилович", manager: 2 },
      { id: 14, photo: "", name: "Гладков Захар Артёмович", manager: 3 },
      { id: 15, photo: "", name: "Макаров Илья Дмитриевич", manager: 1 },
      { id: 16, photo: "", name: "Кузнецов Кирилл Гордеевич", manager: 1 },
      { id: 17, photo: "", name: "Симонова Василиса Васильевна", manager: 4 },
      { id: 18, photo: "", name: "Муравьева Алина Руслановна", manager: 3 },
      { id: 19, photo: "", name: "Борисов Михаил Сергеевич", manager: 1 },
      { id: 20, photo: "", name: "Иванова Милана Матвеевна", manager: 3 },
      { id: 21, photo: "", name: "Столярова Анна Олеговна", manager: 3 },
      { id: 22, photo: "", name: "Покровский Лев Дмитриевич", manager: 1 },
      { id: 23, photo: "", name: "Андреева Вера Львовна", manager: 1 },
      { id: 24, photo: "", name: "Емельянов Артём Давидович", manager: 3 },
      { id: 25, photo: "", name: "Смирнова Виктория Ивановна", manager: 2 },
      { id: 26, photo: "", name: "Зайцева Ева Саввична", manager: 1 },
      { id: 27, photo: "", name: "Романова София Львовна", manager: 2 },
      { id: 28, photo: "", name: "Черных Анатолий Миронович", manager: 2 },
      { id: 29, photo: "", name: "Морозов Владислав Семёнович", manager: 2 },
      { id: 30, photo: "", name: "Щеглов Илья Львович", manager: 1 },
      { id: 31, photo: "", name: "Владимиров Евгений Миронович", manager: 4 },
      { id: 32, photo: "", name: "Белов Артём Артёмович", manager: 3 },
    ],
  };
}
